version: '3.8'

services:
  ururu-ai:
    build:
      target: development
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - .:/app
      - /app/venv
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    ports:
      - "8001:8000"

  # 개발용 Redis (캐싱 및 세션 저장용)
  redis:
    image: redis:7-alpine
    container_name: ururu-ai-redis-dev
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - ururu-network

volumes:
  redis_data:
    driver: local
